In [1]:
import pyttsx3

ModuleNotFoundError: No module named 'pyttsx3'

In [2]:
!pip install pyttsx3

In [5]:
import pyttsx3
engine = pyttsx3.init()
engine.say("Hello everyone, we are in India and we are learning python which requires practice")
engine.runAndWait() # it will convert the output in audio form

In [8]:
import numpy

In [9]:
my_list1 = [15,67,45,34,600]

In [10]:
my_list1

[15, 67, 45, 34, 600]

In [11]:
numpy.array(my_list1)

array([ 15,  67,  45,  34, 600])

In [15]:
arr = numpy.array(my_list1)

In [16]:
arr

array([ 15,  67,  45,  34, 600])

In [17]:
type(arr)

numpy.ndarray

In [18]:
import numpy as np

In [19]:
my_list2 = [1,2,3,4,5,6]

In [20]:
my_list2

[1, 2, 3, 4, 5, 6]

In [21]:
arr2 =np.array(my_list2)

In [22]:
type(arr2)

numpy.ndarray

In [23]:
arr2

array([1, 2, 3, 4, 5, 6])

In [24]:
my_list3 = [[10,11,12],[13,14,15],[16,17,18]]

In [25]:
my_list3

[[10, 11, 12], [13, 14, 15], [16, 17, 18]]

In [26]:
type(my_list3)

list

In [27]:
arr4 = np.array(my_list3)

In [28]:
type(arr4)

numpy.ndarray

In [29]:
arr4

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [30]:
my_tuple1 = (1,2,3,4,5,6)

In [31]:
type(my_tuple1)

tuple

In [32]:
arr5 = np.array(my_tuple1)

In [33]:
type(arr5)

numpy.ndarray

In [34]:
arr5

array([1, 2, 3, 4, 5, 6])

In [35]:
## arrange

In [36]:
range(5,20,2)

range(5, 20, 2)

In [37]:
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [38]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
np.arange(100,500,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225,
       230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
       295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355,
       360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420,
       425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
       490, 495])

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [47]:
np.zeros(20) +89

array([89., 89., 89., 89., 89., 89., 89., 89., 89., 89., 89., 89., 89.,
       89., 89., 89., 89., 89., 89., 89.])

In [48]:
a = np.zeros((4,5))

In [49]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
a.reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [2]:
import numpy as np

In [3]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [5]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(5) #numbers will appear between zero to one

array([0.79545997, 0.4965225 , 0.30604488, 0.12196735, 0.762994  ])

In [10]:
np.random.rand(5,8)

array([[0.38357321, 0.31532447, 0.86804357, 0.76899616, 0.39738691,
        0.17163069, 0.59767286, 0.34546447],
       [0.03140002, 0.25219768, 0.97906873, 0.96745789, 0.39276159,
        0.89086038, 0.84715146, 0.88071196],
       [0.78092868, 0.09686615, 0.73905925, 0.80408473, 0.07609386,
        0.98316482, 0.57660164, 0.61346518],
       [0.316774  , 0.50930978, 0.16554104, 0.80884854, 0.61163401,
        0.150415  , 0.91215574, 0.9186927 ],
       [0.36188068, 0.82101249, 0.1439906 , 0.76038407, 0.34038389,
        0.90105481, 0.15582577, 0.18345805]])

In [11]:
np.random.rand(100)

array([0.21612243, 0.98679889, 0.80581746, 0.71105524, 0.07778158,
       0.49960982, 0.71079392, 0.19397681, 0.12176051, 0.32113658,
       0.35677001, 0.51913123, 0.06309802, 0.04041698, 0.76176718,
       0.82739624, 0.03353022, 0.34718314, 0.32439633, 0.46076107,
       0.3467437 , 0.07076515, 0.28795451, 0.65462037, 0.09549808,
       0.95276612, 0.39908222, 0.29344124, 0.94727093, 0.44758945,
       0.27582369, 0.97643525, 0.82610823, 0.83299431, 0.98014437,
       0.78059937, 0.43353584, 0.19661466, 0.85413163, 0.72111892,
       0.94218906, 0.81304547, 0.67442824, 0.51607418, 0.74503079,
       0.17678606, 0.57384609, 0.74441731, 0.76457806, 0.94071836,
       0.05882991, 0.35756026, 0.10232485, 0.26911566, 0.97246295,
       0.45287939, 0.76643418, 0.390803  , 0.45558824, 0.02274291,
       0.56016748, 0.81425327, 0.63705118, 0.11005001, 0.50822986,
       0.00499769, 0.39784926, 0.71789124, 0.51177601, 0.85867865,
       0.37039138, 0.15544046, 0.41903253, 0.72453348, 0.16617

In [12]:
np.random.randn(5) #randn generate number in standard normal distribution

array([ 1.75676340e+00,  1.27257231e+00, -2.22945110e-01,  1.29239747e-03,
        3.47735068e-01])

In [16]:
np.random.randn(5)

array([ 0.90830799, -2.02806921, -0.98702635, -0.12439967, -1.288949  ])

In [17]:
np.random.randn(10,10)

array([[ 0.60588739,  1.29432298, -0.47412946, -1.78835257,  1.24647592,
        -0.11247504,  1.13185233,  0.99254623, -0.25253657,  0.53314363],
       [-1.29999597, -0.3043639 ,  0.35748641, -0.70652971,  1.20525261,
        -1.5292199 ,  1.31710672,  0.36798724, -1.92811582, -0.24127586],
       [ 0.1483832 , -2.40769633,  0.79152186, -1.76342438, -0.7381865 ,
         0.62111189, -1.44705207,  0.24506768, -1.57826021,  0.14790858],
       [ 0.12308518, -0.86492589,  1.48592567, -0.51996531,  0.00654169,
         1.24550201,  0.10859481,  0.3056949 , -0.13659868,  0.0584088 ],
       [ 0.94091997,  0.35031308,  0.6555338 ,  0.34885438,  1.41354615,
        -0.3961665 , -0.23914479, -0.11907473,  0.32264973,  0.10693756],
       [-0.56486136, -0.03286897,  0.77243275, -0.20166473,  0.32241817,
        -0.97365402, -0.41891271, -1.82659987,  0.88814343, -0.74048553],
       [-0.94931414, -0.24240006,  0.75179881, -0.42098754, -1.01349002,
        -0.0903136 ,  0.14188023,  0.56329957

In [19]:
np.random.randn(5,4)

array([[ 0.7343088 ,  0.28815444, -0.26530077, -0.15155931],
       [ 1.46763176, -0.80533112,  1.27618985,  1.02265777],
       [-0.56396387, -0.71981625,  0.33002144,  1.45567064],
       [ 1.06434927,  0.00469876, -2.11741192,  0.52124901],
       [ 1.45319308,  0.76134993, -3.22549083,  0.0997048 ]])

In [33]:
np.random.randint(5)

4

In [39]:
np.random.randint(5,20)

12

In [40]:
np.random.randint(10,30,8)

array([13, 26, 22, 21, 17, 21, 29, 19])

In [45]:
np.random.randint(-10,10,5)

array([-1, -3,  0, -6,  5])

In [46]:
np.random.randint(2,4,5)

array([2, 2, 3, 3, 3])

In [47]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranarr = np.random.randint(0,50,10)

In [52]:
ranarr

array([47, 47, 20, 48, 11, 46, 15, 34, 33, 18])

In [54]:
arr.shape

(25,)

In [55]:
ranarr.shape

(10,)

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [62]:
ranarr

array([47, 47, 20, 48, 11, 46, 15, 34, 33, 18])

In [63]:
ranarr.max()

48

In [64]:
ranarr.min()

11

In [65]:
np.max(ranarr) #another method to get max value in array

48

In [66]:
np.min(ranarr) #another method to get min value in array

11

In [67]:
ranarr.argmax() #index position of maximum value in array

3

In [68]:
ranarr.argmin()  #index position of minimum value in array

4

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
arr.dtype

dtype('int32')

In [74]:
#Indexing

In [76]:
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[5]

5

In [79]:
arr[4:8]

array([4, 5, 6, 7])

In [80]:
arr_new = arr[4:8]

In [81]:
arr_new

array([4, 5, 6, 7])

In [82]:
arr_new[1:3]

array([5, 6])

In [83]:
arr_new[1:3] = 78

In [84]:
arr_new

array([ 4, 78, 78,  7])

In [85]:
arr #this concept is broadcasting it will affect main array also just like it addfect here

array([ 0,  1,  2,  3,  4, 78, 78,  7,  8,  9, 10])

In [87]:
arr = np.arange(0,11)

In [88]:
arr_copy = arr.copy() #everytime it is necessary to keep copy of orginal array

In [89]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.random.randint(2,3)

2

In [7]:
np.arange(2,3,0.2)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [13]:
np.random.randn(10,15) #its generate numbers using standard normal distribution

array([[-0.10045618,  0.31854969,  0.90902583, -1.48612888, -1.02304161,
         0.38297031, -1.47106551,  2.49237935, -0.71910572, -0.60852313,
        -0.25173569,  0.94031239, -0.49298849, -0.38329074, -0.65940699],
       [ 0.35521241,  1.44462342,  1.74176614,  0.5836335 , -0.05715477,
        -1.55392439, -0.56958767, -0.38118255,  0.44139318,  0.58105696,
         0.23079866, -1.21063841, -0.35965917,  0.09735888,  0.39537549],
       [ 0.24587551,  0.58404185,  1.12862667, -0.32798351, -0.62885895,
        -0.39391884, -1.26025967, -1.17642913, -0.75038561, -0.41455403,
        -0.3881596 , -0.58361761, -0.52316926,  0.0066995 ,  0.72499248],
       [ 0.33552049, -2.28386486,  0.92279391, -0.49230197, -0.48607245,
         0.79641383, -0.75345059, -0.23395281, -1.18224794, -0.12941708,
         1.93267677, -1.76200527, -0.56490961,  0.8217922 ,  1.03351964],
       [ 0.06633567,  1.01188773,  0.581631  ,  1.82732002,  0.33766869,
        -1.38147487, -1.08248931,  0.15901045, 

In [9]:
np.arange(2,3,0.3)

array([2. , 2.3, 2.6, 2.9])

In [14]:
import random

In [15]:
random.random()

0.4122076858447945

In [25]:
random.randrange(2,10,2)

8

In [28]:
np.random.rand(10)*5

array([1.98099018, 3.33621552, 1.80144671, 2.72606395, 4.53506987,
       3.8181353 , 4.32969725, 1.17520081, 2.73258496, 3.24015943])

In [29]:
import numpy as np

In [32]:
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [33]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr2d[1,2]

30

In [35]:
arr2d[2,1]

40

In [36]:
arr2d[0:2,1]

array([10, 25])

In [37]:
arr2d[0:2,1:2]

array([[10],
       [25]])

In [38]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [40]:
arr2d[[0,1],[0,1]]

array([ 5, 25])

In [43]:
arr2d[0:,1]

array([10, 25, 40])

In [48]:
arr2d[0:,1:2]

array([[10],
       [25],
       [40]])

In [50]:
arr2d[2,0:]

array([35, 40, 45])

In [1]:
import numpy as np

In [2]:
matrix = np.arange(1,26)

In [3]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [4]:
matrix = np.arange(1,26).reshape(5,5)

In [5]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
matrix[2,2:4] #for one dimensional array

array([13, 14])

In [12]:
matrix[2:3,2:4] #for two dimensional array

array([[13, 14]])

In [13]:
matrix[0:3,1:2] #for two dimension

array([[ 2],
       [ 7],
       [12]])

In [14]:
matrix[0:3,1] #for one dimension

array([ 2,  7, 12])

In [18]:
matrix[1:3,3:4]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [19]:
matrix[2:4,1:4]

array([[12, 13, 14],
       [17, 18, 19]])

In [21]:
matrix[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
matrix[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
matrix[:,3:4]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [26]:
matrix[[1,3],[1,3]] #[row,row],[column,column]

array([ 7, 19])

In [28]:
matrix[[0,4],[0,4]]

array([ 1, 25])

In [29]:
matrix[[0,4],[0,3]]

array([ 1, 24])

In [30]:
matrix.sum() #sum of all numbers in the matrix

325

In [31]:
np.sum(matrix)

325

In [32]:
matrix.std()  #Standard Deviation

7.211102550927978

In [34]:
matrix.sum(axis=1) #row

array([ 15,  40,  65,  90, 115])

In [36]:
matrix.sum(axis=0) #column

array([55, 60, 65, 70, 75])

# Fancy Indexing

In [40]:
array2d = np.zeros((10,10))

In [41]:
array2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
array2d.shape

(10, 10)

In [43]:
array2d.shape[1]

10

In [44]:
arr_length = array2d.shape[1]

In [45]:
arr_length

10

In [52]:
for v in range(arr_length):
    array2d[v] = v

In [53]:
array2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [54]:
array2d[[3,5,7,8]] #this is fancy indexing 

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [55]:
array2d[[1,9,2,3]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [56]:
arr = np.arange(1,11)

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr>7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [59]:
arr[arr>7]

array([ 8,  9, 10])

In [60]:
x = 4
arr[arr>x]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr =np.arange(0,10)

In [63]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [67]:
arr/arr #nan = not a number

C:\Users\Hp\AppData\Local\Temp\ipykernel_12392\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
1/arr

C:\Users\Hp\AppData\Local\Temp\ipykernel_12392\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [70]:
np.max(arr)

9

In [71]:
np.min(arr)

0

In [72]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [75]:
np.log(arr)

C:\Users\Hp\AppData\Local\Temp\ipykernel_12392\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [1]:
import numpy as np

In [2]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
lst=np.arange(0.01,1.01,0.01)
lst.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])